### ISSUE TITLE
Add axios in package.json

### ISSUE THREAD

**Issue by ThomasG77** [sakitam-fdd/wind-layer#1]
When I try your code locally, your demo https://github.com/sakitam-fdd/wind-layer/blob/master/examples/index.html is not working directly.
This is due to the fact that the code references `../node_modules/axios/dist/axios.js` but axios is not declared in your `package.json`.
Doing `npm install axios` solves the issue.

You may want to change your package.json accordingly.

**Comment by sakitam-fdd** [comment]
Thanks for your issue, I added axios to devDependencies. However, in fact axios is an external reference library，the better way is to use cdn。
