### ISSUE TITLE
mapbox-gl 中使用 mapbox-wind 1.1.0 +性能问题

### ISSUE THREAD

**Issue by ShareQiu1994** [sakitam-fdd/wind-layer#102]
使用mapbox-wind 1.1.0 的ScalarFill，出现在拖动、缩放过程中有较为严重的性能问题。 在1.0.0并不没有这样的问题。

以下为我的代码：

```
 <script>
      mapboxgl.accessToken =
        'pk.eyJ1IjoibWFwYm94IiwiYSI6ImNpejY4M29iazA2Z2gycXA4N2pmbDZmangifQ.-g_vE53SD2WrJ6tFX7QHmA';
      const map = new mapboxgl.Map({
        container: 'map',
        style: {
          version: 8,
          sources: {
            carto: {
              type: 'raster',
              tiles: [
                '//a.basemaps.cartocdn.com/dark_all/{z}/{x}/{y}.png',
                '//b.basemaps.cartocdn.com/dark_all/{z}/{x}/{y}.png',
                '//c.basemaps.cartocdn.com/dark_all/{z}/{x}/{y}.png',
                '//d.basemaps.cartocdn.com/dark_all/{z}/{x}/{y}.png',
              ],
              tileSize: 256,
            },
          },
          layers: [
            {
              id: 'carto',
              type: 'raster',
              source: 'carto',
              paint: {
                'raster-resampling': 'nearest',
                'raster-fade-duration': 0,
              },
            },
            {
              id: 'background',
              type: 'background',
              layout: {
                visibility: 'none',
              },
            },
          ],
        },
        center: [113.53450137499999, 34.44104525],
        zoom: 0,
      });

      const color = {
        temp: [
          [54, [215, 25, 28, 255]],
          [82, [253, 174, 97, 255]],
          [111, [255, 255, 191, 255]],
          [140, [171, 221, 164, 255]],
          [169, [43, 131, 186, 255]],
        ],
      };

      map.on('load', function() {
        const tempInterpolateColor = color.temp.reduce(
          (result, item, key) =>
            result.concat(item[0], 'rgba(' + item[1].join(',') + ')'),
          [],
        );
        const fillLayer = new mapboxWind.ScalarFill(
          'wind',
          {
            type: 'image',
            url: './data/icon_teplota_2_m_20200728_03.jpg',
            extent: [
              [-180, 85.051129],
              [-180, -85.051129],
              [180, 85.051129],
              [180, -85.051129],
            ],
            width: 720,
            height: 360,
            renderForm: 'r',
            min: 0,
            max: 255,
          },
          {
            wrapX: true,
            styleSpec: {
              'fill-color': [
                'interpolate',
                ['linear'],
                ['get', 'value'],
                ...tempInterpolateColor,
              ],
              opacity: 1,
            },
            renderForm: 'r',
            widthSegments: 720,
            heightSegments: 360,
          },
        );
        map.addLayer(fillLayer);
      });
    </script>
```

当我使用1.0.0版本时：
![1 0 0 00_00_00-00_00_30](https://user-images.githubusercontent.com/19948086/115978160-36f84700-a5b0-11eb-90de-dd7e780da789.gif)

当我使用1.1.0版本时：
![1 1 0 00_00_00-00_00_30](https://user-images.githubusercontent.com/19948086/115978165-4081af00-a5b0-11eb-9e01-d79d6c64bd21.gif)

我想这可能在mapbox中是一个Bug，希望能得以修复

**Comment by sakitam-fdd** [comment]
@ShareQiu1994 
这两个参数如果你不需要映射高度不需要设置或者设置为
```js
widthSegments: 1,
heightSegments: 1,
```

这两个参数是为了映射高度预留的：https://codepen.io/sakitam-fdd/pen/GRpeeGG

**Comment by ShareQiu1994** [comment]
非常感谢！这解决了我的问题。 我会持续关注，这是一个很棒的项目

**Comment by ShareQiu1994** [comment]
@sakitam-fdd 
大佬，还有个问题咨询下你，在1.0.0版本 ScalarFill可以设置颜色透明度，在1.1.0中同样的代码无法生效，在1.1.0 +中是需要添加新的设置吗，或是本身不支持？？ 

我的代码：
![F~CXH_%C(TZ @}ZH9BGF)GK](https://user-images.githubusercontent.com/19948086/115979982-bccdbf80-a5bb-11eb-824d-a98206230dd0.png)


1.0.0 版本中：
![84Q5TPR` $A1ADRIV28%E2](https://user-images.githubusercontent.com/19948086/115979814-b428b980-a5ba-11eb-9cce-dbf4aa633d09.png)

1.1.0版本中：
![R__$4CP Q%XOD6EQIXC3$37](https://user-images.githubusercontent.com/19948086/115979929-5fd20980-a5bb-11eb-92de-07ba85c56661.png)

**Comment by ShareQiu1994** [comment]
具体代码：
`
   const fillLayer = new mapboxWind.ScalarFill(json.name, {
            'type': 'image',
            'url': json.url,
            'extent': [
                [-180, 85.051129],
                [-180, -85.051129],
                [180, 85.051129],
                [180, -85.051129]
            ],
            'width': 720,
            'height': 360,
            'min': json.min,
            'max': json.max
        }, {
            wrapX: true,
            styleSpec: {
                'fill-color': [
                    'interpolate',
                    ['linear'],
                    ['get', 'value'],
                    ...tempInterpolateColor
                ],
                opacity: 1
            },
            renderForm: 'r',
            widthSegments: 1,
            heightSegments: 1
        })
        this.map.addLayer(fillLayer)
`

**Comment by ShareQiu1994** [comment]
经测试，最新的https://cdn.jsdelivr.net/npm/@sakitam-gis/mapbox-wind@1.1.1-alpha.2/dist/mapbox-wind.min.js   已解决。

**Comment by sakitam-fdd** [comment]
1.1.1-alpha.1 可能是没开 blend，后面会完善测试流程
