### ISSUE TITLE
支持 openlayers 6.5

### ISSUE THREAD

**Issue by norangit** [sakitam-fdd/wind-layer#107]
作者大大，有没有计划啥时候支持 openlayers 6.5 啊？

**Comment by norangit** [comment]
昨晚搞了半天支持ol6.5，发现 api 变化很大，很多 api 在 ol 6.5 里已经不再被导出了，所以导致wind-layer 无法运行，我目前的做法是把ol 6.5 整个src 放在目录下，然后修改 import 路径，然后build 出来，大小还行，2000多行 dev 版，不过渲染出来的风效果和作者的demo 图片不太一样(꒦_꒦)

**Comment by SmallShare** [comment]
ol6 插件引入后，报错WindLayer is not defined
