### ISSUE TITLE
ol6 删除添加问题

### ISSUE THREAD

**Issue by shangdiWu** [sakitam-fdd/wind-layer#112]
1、如果初始化时设置属性 map : map, 更新图层调用windlayer.setData(data) 不生效

![捕获](https://user-images.githubusercontent.com/28294395/124231849-693f9b00-db43-11eb-8f94-3eb751f834f9.PNG)

这里修改为renderer.oRender.setData(data) -> renderer.oRender.setData(this.field); 即可  第1353行代码

2、移动或缩放时 粒子会乱掉 1秒内恢复 可能是重新插值的问题

**Comment by sakitam-fdd** [comment]
@shangdiWu 第一个问题已经修复，第二个问题暂时先设置 `forceRender = false`, 这样在地图交互的过程中会先隐藏图层，目前来说在 canvas 的实现无法解决这个问题。
