### ISSUE TITLE
在WindLayer实例添加到地图之后，添加其他矢量图层无法显示，但是在之前添加到地图的正常，这是什么原因？

### ISSUE THREAD

**Issue by WebScholar** [sakitam-fdd/wind-layer#113]
// 添加风场图之前添加的矢量图层显示正常
map.addLayer(vectorLayer);

// 添加风场图
map.addLayer(windLayer);

// 添加风场图之后添加的矢量图层无法显示
map.addLayer(vectorLayer);

**Comment by sakitam-fdd** [comment]
能否给一个复现示例，有可能和 wind-core 的逻辑有关系

**Comment by IdenPin** [comment]
@WebScholar   我也遇到了，风向图层最后使用 windLayer.setMap(this.map)，其它图层最后显示就没问题了。

**Comment by IdenPin** [comment]
同样有这样的问题，好郁闷。只能使用setMap添加才可以，但是这种方式缩放地图生成的粒子风会来回闪动最后才趋于稳定。 @ @sakitam-fdd

**Comment by 2sheep2simp1e** [comment]
windLayer设置透明度为1以下也可以解决，比如windLayer.setOpacity(0.9)，0.1的透明度不影响看，但是其他图层神奇地又出现了。。

**Comment by 2sheep2simp1e** [comment]
@WebScholar windLayer设置透明度为1以下也可以解决，比如windLayer.setOpacity(0.9)，0.1的透明度不影响看，但是其他图层神奇地又出现了。。

**Comment by sakitam-fdd** [comment]
@IdenPin @WebScholar @2sheep2simp1e 导致这个问题的原因主要是 ol 内部 renderer 的 canvas 复用逻辑，现在强制 wind-layer 独占一个 canvas
