### ISSUE TITLE
基于高德实现的风场插件amap-wind不支持高德2.0的问题

### ISSUE THREAD

**Issue by seanhuqi** [sakitam-fdd/wind-layer#123]
作者你好，我想问一下现目前版本的高德风场插件只支持高德1.x的吗？因为我现在遇到的问题是使用2.0版本的高德会报错，1.4的可以正常跑起来，但是项目需求目前尽量是想使用2.0版本的高德，性能会好些，对于兼容2.0有什么解决方法吗？

**Comment by sakitam-fdd** [comment]
高德和百度的未来将不会再迭代，如果有需求可以 fork 一下修改，核心实现方式后面会完善，可以基于此来进行修改。
