### ISSUE TITLE
openlayer6地图层级变化时，粒子流加速

### ISSUE THREAD

**Issue by fbbhaha** [sakitam-fdd/wind-layer#127]
openlayer6每次地图层级变化时，粒子流会有个突然加速的动画，这个通过怎么设置可以去除掉嘛？

**Comment by IdenPin** [comment]
通过setMap设置的好像都有这个问题，这个也困扰了我很久。同求解决方案

**Comment by fbbhaha** [comment]
> duplicate #112
好滴，感谢大佬解答
