### ISSUE TITLE
高德地图下缩放和移动

### ISSUE THREAD

**Issue by novrain** [sakitam-fdd/wind-layer#14]
尝试了样例中的amap.html，在移动和缩放时，风场的位置偏移，也没有什么规律。
另外，移动时是否需要重绘？
不知道现在还有时间维护修复？也想参与修改，奈何GIS方面知识欠缺...
感谢!

**Comment by sakitam-fdd** [comment]
@novrain 先欢迎参与，再说下问题。
1. 最近一两个月左右，暂时没精力投入这个事，不过如果你那边有想法我可以先记下 😄 。
2. 位置偏移这个问题的解决需要重构现在代码了，工作量比较大，在分支上已经做了一部分工作了，主要是将位置坐标和屏幕像素的转换修改为 某个地图引擎的内置方式，而不是采用  windyjs，这样就能保证每次重绘时位置信息时没有偏移的。
3. 无论放大缩小，平移，旋转这些地图操作都是需要重绘的，实际地图引擎也是这种实现方式的，努力方向主要是减少重绘和绘制效率，不重绘渲染是做不到的 😸 .

**Comment by novrain** [comment]
感谢回复，理解工作冲突，我这边继续关注了。
嗯，确实平移需要重绘
