### ISSUE TITLE
how to overlay windLayer in multi worlds in ol6

### ISSUE THREAD

**Issue by Alley0911** [sakitam-fdd/wind-layer#143]
i want to show wind stream in multi worlds, i tried to add attribute "wrapX", but it does't work
i'll appreciate it if you could tell me how to do that.
by the way, i use openlayers 6.

**Comment by sakitam-fdd** [comment]
@Alley0911 https://blog.sakitam.com/wind-layer/guide/index#ol-wind-%E5%8F%82%E6%95%B0%E8%AF%B4%E6%98%8E
