### ISSUE TITLE
Module not found: Error: Can't resolve 'worker_threads' in '\node_modules\@sakitam-gis\mapbox-wind\dist'

### ISSUE THREAD

**Issue by harveyli1013** [sakitam-fdd/wind-layer#153]
在非node环境下，或在react或vue框架下引入 '@sakitam-gis/mapbox-wind'，导致编译报错；
`
import { WindLayer, ScalarFill } from '@sakitam-gis/mapbox-wind';

`
![1654578984277](https://user-images.githubusercontent.com/99250782/172301313-f0fd1ad1-f224-4127-bd01-a09b34e2d5ce.png)

原因为，在非node环境下执行源码中以下的逻辑；

var WorkerClass = null;
`
try {
    var WorkerThreads =
        typeof module !== 'undefined' && typeof module.require === 'function' && module.require('worker_threads') ||
        typeof __non_webpack_require__ === 'function' && __non_webpack_require__('worker_threads') ||
        typeof require === 'function' && require('worker_threads');
    WorkerClass = WorkerThreads.Worker|false;
} catch (e) {
} // eslint-disable-line
`

而在浏览器环境下，是没有 `worker_threads`模块的；麻烦改一下；或给出较好的解决方案；

**Comment by harveyli1013** [comment]
对了，使用的mapbox-wind中的example

**Comment by sakitam-fdd** [comment]
@harveyli1013 使用的@sakitam-gis/mapbox-wind版本，webpack 的版本还有 nodejs 的版本能否提供一下？
