### ISSUE TITLE
Background without transparency

### ISSUE THREAD

**Issue by larsurilch** [sakitam-fdd/wind-layer#159]
I'm using Openlayers 6.5 and when I add it as in the example the background is white.

```
import { WindLayer } from 'ol-wind';

const windLayer = new WindLayer(res, {
    forceRender: false,
    windOptions: {
      velocityScale: 1 / 20,
      paths: 5000,
      colorScale: () => {
        return '#ff473c';
      },
      width: 3,
      generateParticleOption: false
    }
});

map.addLayer(windLayer);
```

![background](https://user-images.githubusercontent.com/251246/180805762-488f7663-d639-4075-9183-3b0660663cf9.png)

When I use the **map as an option** it works with transparency but I have problems removing the layer.

```
import { WindLayer } from 'ol-wind';

new WindLayer(res, {
    forceRender: false,
    windOptions: {
      velocityScale: 1 / 20,
      paths: 5000,
      colorScale: () => {
        return '#ff473c';
      },
      width: 3,
      generateParticleOption: false
    },
    map: map
});
```

![transparent](https://user-images.githubusercontent.com/251246/180806359-11ad3977-0897-4dda-87b2-28df6a36923d.png)

Are there any parameters to solve the transparency problem? 

Thanks

**Comment by sakitam-fdd** [comment]
@larsurilch use `windLayer.setMap(null);` remove layer and `windLayer.setMap(map);` add layer is it feasible?

**Comment by sakitam-fdd** [comment]
@larsurilch try v1.1.1，close this issues for now, unless there is another problem
