### ISSUE TITLE
解析grib数据还是失败

### ISSUE THREAD

**Issue by liuwuqingnian** [sakitam-fdd/wind-layer#16]
生成的是一个空json文件，并且页面上返回的是   无法访问网站

**Comment by sakitam-fdd** [comment]
@liuwuqingnian 本地启动无数据时有什么报错信息吗，可以方便贴一下吗

**Comment by sakitam-fdd** [comment]
@liuwuqingnian windows下偶发，linux下暂时是权限问题，修改一下就可以了 [测试](http://58.87.95.84:3030/getdata?time=1536917431397)

**Comment by sakitam-fdd** [comment]
@liuwuqingnian link #21
