### ISSUE TITLE
chrome 106 version bug

### ISSUE THREAD

**Issue by oneninedev** [sakitam-fdd/wind-layer#167]
你好 sakitam在此次更新的chrome 106 version中,发现了wind-layer运行时chrome停止的现象。106 version进行更新计划吗?提前跟大家说一声谢谢

Hello, sakitam
In the recently updated Chrome 106 version, Chrome was found to stop when wind-layer was executed.
Do we proceed with the update plan in 106 version?
I'd like to thank you in advance :)

**Comment by sakitam-fdd** [comment]
fixed in version v1.1.1
