### ISSUE TITLE
怎样获取某一个位置的风向，风速和温度信息

### ISSUE THREAD

**Issue by liuwuqingnian** [sakitam-fdd/wind-layer#17]
怎样获取某一个位置的风向，风速和温度信息

How to get wind direction, wind speed and temperature information of a certain location

**Comment by sakitam-fdd** [comment]
- 都提供了 `getPointData ` 方法，相关示例可以查看 [ol示例](https://github.com/sakitam-fdd/wind-layer/blob/24da40095f0c40a5cd1eaa3d65fa8fdd81200d5c/examples/index.html#L95), 其他插件也是类似。
- 接收一个参数 `coordinates ` - 鼠标位置坐标，返回风向，风速信息，目前上个版本已经将温度分量移除了，暂不支持温度获取了。
