### ISSUE TITLE
openlayers6下没有对应地图平铺显示

### ISSUE THREAD

**Issue by wenlc000** [sakitam-fdd/wind-layer#170]
大神，请问这种情况如何解决！急！！！
![1667790822532](https://user-images.githubusercontent.com/49868062/200219306-58c300b9-2581-41c0-a18c-c0d68eb998f8.png)

**Comment by wenlc000** [comment]
![Uploading 1667791141803.png…]()
@sakitam-fdd

**Comment by sakitam-fdd** [comment]
@wenlc000 https://blog.sakitam.com/wind-layer/guide/index#ol-wind-%E5%8F%82%E6%95%B0%E8%AF%B4%E6%98%8E
