### ISSUE TITLE
色斑图必须采用图片吗？

### ISSUE THREAD

**Issue by wjfsdbd** [sakitam-fdd/wind-layer#177]
请问色斑图的数据格式到底是如何的？目前有栅格的温度数据，请问要如何投入到色斑图中？另外nc格式的数据是否有现成插件可以转成展示所需的JSON呢？

**Comment by lovewxz** [comment]
同上，色斑图偏移严重，但粒子图就很正常

**Comment by lovewxz** [comment]
> @lovewxz 偏移是指？可以提供个 demo 吗

[wind-global-all.json.zip](https://github.com/sakitam-fdd/wind-layer/files/11269167/wind-global-all.json.zip)
这个风粒子图很正常，色斑图不知道为什么变形了

**Comment by echohye** [comment]
> @wjfsdbd 看下 https://github.com/sakitam-gis/raster-process 常规是处理成 4326 的单张图片，后续（本月）会支持瓦片和墨卡托投影的瓦片（png、jpeg、tiff）

https://github.com/sakitam-gis/raster-process 请问这个程序什么时候可以支持瓦片和墨卡托投影的瓦片？

**Comment by echohye** [comment]
> > @wjfsdbd 看下 https://github.com/sakitam-gis/raster-process 常规是处理成 4326 的单张图片，后续（本月）会支持瓦片和墨卡托投影的瓦片（png、jpeg、tiff）
> 
> @sakitam-fdd https://github.com/sakitam-gis/raster-process 请问这个程序什么时候可以支持瓦片和墨卡托投影的瓦片？

@sakitam-fdd 请问这个有计划吗

**Comment by sakitam-fdd** [comment]
@echohye 新版本已经支持了墨卡托的瓦片和单张哈，旧版的 4326 的单张图已经取消支持
https://blog.sakitam.com/wind-layer/guide/data.html

https://blog.sakitam.com/wind-layer/playgrounds/mapbox-gl/colorize.html

**Comment by echohye** [comment]
> @echohye 新版本已经支持了墨卡托的瓦片和单张哈，旧版的 4326 的单张图已经取消支持 https://blog.sakitam.com/wind-layer/guide/data.html
> 
> https://blog.sakitam.com/wind-layer/playgrounds/mapbox-gl/colorize.html

https://github.com/sakitam-gis/raster-process请问这个程序后续会支持netcdf吗，生成的瓦片和windy的瓦片是一样的吗是😯

**Comment by echohye** [comment]
> @echohye 新版本已经支持了墨卡托的瓦片和单张哈，旧版的 4326 的单张图已经取消支持 https://blog.sakitam.com/wind-layer/guide/data.html
> 
> https://blog.sakitam.com/wind-layer/playgrounds/mapbox-gl/colorize.html

@sakitam-fdd  [raster-process](https://github.com/sakitam-gis/raster-process)请问这个项目后续会支持netcdf吗，生成的瓦片和windy的瓦片是一样的吗😯

**Comment by sakitam-fdd** [comment]
@echohye 目前应该是支持的，核心是 gdal，这种标准科学数据都是可以使用的

**Comment by echohye** [comment]
> @echohye 目前应该是支持的，核心是 gdal，这种标准科学数据都是可以使用的

好的谢谢大佬
