### ISSUE TITLE
how to add the temperture or other layers

### ISSUE THREAD

**Issue by NanXunbiubiu** [sakitam-fdd/wind-layer#18]
怎么实现添加温湿度图层，而且播放时没有内存泄漏问题

**Comment by sakitam-fdd** [comment]
这个属于ol的图层叠加和操作了，可以描述一下图层类型和场景吗

**Comment by sakitam-fdd** [comment]
@NanXunbiubiu 这个属于ol的图层叠加和操作了，可以描述一下图层类型和场景吗

**Comment by NanXunbiubiu** [comment]
> @NanXunbiubiu 这个属于ol的图层叠加和操作了，可以描述一下图层类型和场景吗

ok, 数据来源也是 gsf，我打算用ol实现温湿度图层和wind叠加在一起（参考：https://map.zq12369.com），并且可以播放，图层类型也是ImageCanvas，相当于我在ol上叠加两个ImageCanvas图层，一个是wind，另个是温度或者湿度，气压之类（new windLayer.OlWind，new两次），我目前的遇到的问题是：图层可以叠加，但是在播放几次之后浏览器会特别卡顿，我F12查看了没有内存泄漏问题

**Comment by sakitam-fdd** [comment]
@NanXunbiubiu 意思就是叠加了两个层，播放时一直添加移除，然后卡顿严重是吗，我抽时间试下看看

**Comment by NanXunbiubiu** [comment]
> @NanXunbiubiu 意思就是叠加了两个层，播放时一直添加移除，然后卡顿严重是吗，我抽时间试下看谢啦，一开始还行但后来就很卡，而且我觉得用canvasFunction写的风场是错误的，怎么说呢，比如你用一个区域风场数据试一下（中国区域的风场），canvasFunction会始终画满整个屏幕，但是区域风场在zoom=3时，应该只能看到数据经纬度之间有风，其他区域是没有风的
