### ISSUE TITLE
风流场渲染之后，其他的交互会导致其重新渲染，底图加载也是如此😂😂😂😂

### ISSUE THREAD

**Issue by zhaoYun-Long** [sakitam-fdd/wind-layer#180]
我用的是openlayer6，ol-wind，有大佬能给出解决方案吗😣😣😣😣😣

**Comment by sakitam-fdd** [comment]
duplicate #100

**Comment by sakitam-fdd** [comment]
@zhaoYun-Long @zhaoYun-Long https://codesandbox.io/p/sandbox/ol-wind-inter-h53m65 先用示例里面的 wind-core 和 ol-wind 试下应该是正常的，这个里面的包是修改了其他问题（移除后重新叠加动画不执行和 layer.setMap方式叠加图层），暂时没有发版

**Comment by sakitam-fdd** [comment]
@zhaoYun-Long 试下 https://www.npmjs.com/package/ol-wind/v/1.1.4

试下还有没其他问题，如果有的话请继续反馈
