### ISSUE TITLE
The mapbox-wind's particles and scalarFill layer cannot overlap with each other

### ISSUE THREAD

**Issue by echohye** [sakitam-fdd/wind-layer#184]
Why do we need to use two different images for the example? and the color spot image and particle layer seem to overlap.
![image](https://github.com/sakitam-fdd/wind-layer/assets/81301702/14d5c8f7-7290-478c-8f06-9abfc831852c)

But when I use the same image, it seems like can't overlap each other.
![image](https://github.com/sakitam-fdd/wind-layer/assets/81301702/8ce23c57-36b2-470b-b396-7fe487d7b2f1)

**Comment by echohye** [comment]
Can we just use one image to make two layers overlap each other😃
![image](https://github.com/sakitam-fdd/wind-layer/assets/81301702/7f08e03c-f195-4f49-8e35-50a24efde4d0)

**Comment by sakitam-fdd** [comment]
@echohye I noticed that you may be looking at an older version of the example，In the old version, the color map used epsg:4326 and the particle layer used epsg:3857, they can't be mixed.

After version 2.0.0-alpha, it may be possible to harmonize the data source source (of course, there are other issues at the moment, and it's still not really very harmonized), and use standard Mercator projection data tiles whenever possible, as detailed in the https://github.com/sakitam-fdd/wind-layer/blob/master/examples/wind-particles.html.

But it's not perfect yet, I can take it and perfect it, but not right now

**Comment by sakitam-fdd** [comment]
release in https://github.com/sakitam-fdd/wind-layer/releases/tag/%40sakitam-gis%2Fmapbox-wind%402.0.0

examples：

- https://github.com/sakitam-fdd/wind-layer/blob/master/examples/wind-particles.html
- https://github.com/sakitam-fdd/wind-layer/blob/master/examples/wind-arrow.html
- https://github.com/sakitam-fdd/wind-layer/blob/master/examples/timeline-pattern.html
