### ISSUE TITLE
色斑图错位

### ISSUE THREAD

**Issue by rapinchen** [sakitam-fdd/wind-layer#186]
色斑图跟实际数据位置对不上，色板图相对实际数据偏南了一些，会是什么原因？

**Comment by rapinchen** [comment]
![image](https://github.com/sakitam-fdd/wind-layer/assets/93891516/06ffa6e5-d92c-436e-a473-64071b6ff9e2)
红色是原图，绿色是渲染后的，对不上。原图直接叠加位置对的

**Comment by sakitam-fdd** [comment]
@rapinchen 方便提供一下数据吗，我来测试下

**Comment by rapinchen** [comment]
@sakitam-fdd 数据已发邮件

**Comment by rapinchen** [comment]
@sakitam-fdd 妥了，感谢大佬无私奉献，世界因你更美丽

**Comment by rapinchen** [comment]
@sakitam-fdd 
大佬最近提供的[maptalks-wind.js.zip](https://github.com/sakitam-fdd/wind-layer/files/12551226/maptalks-wind.js.zip)，
setData更新数据无法重绘，
看了下源码发现在setData方法里，有个
if (this.data && renderer2 && renderer2.scalarFill) {
   renderer2.scalarFill.setData(this.data, (status) => {
   ....
  
  renderer2中没有scalarFill，所以一直无法重绘，尝试改成scalarRender，如下：
        if (this.data && renderer2 && renderer2.scalarRender) {
          renderer2.scalarRender.setData(this.data, (status) => {
          ...
    解决了，不知道是不是一个BUG，这里反馈下。
