### ISSUE TITLE
ol-wind加载流场 在隐藏图层/显示图层 后流场的流动效果停止

### ISSUE THREAD

**Issue by stdue** [sakitam-fdd/wind-layer#189]
在流场图层渲染完成后使用 setVisible 隐藏了该图层，再次使用 setVisible 显示该图层后，流场的流动效果消失，并且变得不会跟随地图的平移或缩放来进行移动，打开控制台也没有任何报错
奇怪的是，同一公司的同事使用一套相同的代码就没有这个问题，仔细比对代码也没有发现任何相差之处，想问一下这是因为什么原因呢？

**Comment by sakitam-fdd** [comment]
@stdue 能提供可复现代码吗，这个原因可能比较复杂，ol 内部 canvas 有可能会被复用，如果被复用的话问题可能比较多

**Comment by sakitam-fdd** [comment]
暂时先关闭，未复现此问题, 可以先用 ol-wind 1.1.9 或者以上版本。可以查看此示例：https://stackblitz.com/edit/vitejs-vite-bwpt4l?file=src%2Fmain.ts
