### ISSUE TITLE
高德地图在viewMode: '2D'下不能使用

### ISSUE THREAD

**Issue by acodercat** [sakitam-fdd/wind-layer#19]
高德地图在viewMode: '2D'下不能使用，具体原因是
![image](https://user-images.githubusercontent.com/16076835/53301561-8599e180-387e-11e9-8efd-ae5dbc574269.png)

**Comment by sakitam-fdd** [comment]
@acodercat 暂时在 v0.0.7版本兼容了一下，但是3D倾斜视图下这个插件暂时无法处理，如果可以的话webgl版本请持续关注 [webgl-wind](https://github.com/sakitam-gis/webgl-wind)
