### ISSUE TITLE
粒子绘制过程中会产生轨迹残留，影响视觉效果，如何解决呢。求助，急！！！

### ISSUE THREAD

**Issue by wenlc000** [sakitam-fdd/wind-layer#190]
![微信图片_20231007180947](https://github.com/sakitam-fdd/wind-layer/assets/49868062/9312bc14-ec52-42f1-8216-6678b77ea317)

**Comment by sakitam-fdd** [comment]
暂时先关闭，未复现此问题。可以查看此示例：https://stackblitz.com/edit/avxuqq?file=package.json
