### ISSUE TITLE
风场在跨东经180度时断开

### ISSUE THREAD

**Issue by wangxiaogang94** [sakitam-fdd/wind-layer#193]
问题如下

![20231108152532](https://github.com/sakitam-fdd/wind-layer/assets/51105411/3de22cc6-5ad3-47d6-a628-1d268d61fca4)

但是文档里示例图没有这个问题
![20231108152119](https://github.com/sakitam-fdd/wind-layer/assets/51105411/702d44a9-cc78-4f90-a5bc-ff8be668f9b8)

**Comment by sakitam-fdd** [comment]
@wangxiaogang94 这是两个问题哈：

1. 你使用的应该旧版 @sakitam-gis/mapbox-wind@1.1.2 之前的版本，这个版本是基于 canvas 渲染的，早期版本有个 bug，你可以更新到 1.1.2，新增了`fieldOptions`参数，需要指定` fieldOptions.wrapX` 为`true`：

```bash
npm i @sakitam-gis/mapbox-wind@1.1.2
```

示例如下：

```diff
window.windLayer = new mapboxWind.WindLayer('wind', data, {
    windOptions: {
      // colorScale: (m) => {
      //   // console.log(m);
      //   return '#fff';
      // },
      colorScale: [
        "rgb(36,104, 180)",
        "rgb(60,157, 194)",
        "rgb(128,205,193 )",
        "rgb(151,218,168 )",
        "rgb(198,231,181)",
        "rgb(238,247,217)",
        "rgb(255,238,159)",
        "rgb(252,217,125)",
        "rgb(255,182,100)",
        "rgb(252,150,75)",
        "rgb(250,112,52)",
        "rgb(245,64,32)",
        "rgb(237,45,28)",
        "rgb(220,24,32)",
        "rgb(180,0,35)"
      ],
      // velocityScale: 1 / 20,
      // paths: 5000,
      frameRate: 16,
      maxAge: 60,
      globalAlpha: 0.9,
      velocityScale: 0.01,
      // velocityScale: () => {
      // 	const zoom = map.getZoom();
      // 	return velocityScales[zoom] || 0.01
      // },
      // paths: 10000,
      paths: 3782,
    },
+    fieldOptions: {
+      wrapX: true,
+    },
  });
  console.log(map, window.windLayer);
  // map.addLayer(window.windLayer);
  window.windLayer.addTo(map);
```

2. 文档示例图的时 2.0 版本，基于 webgl 渲染的，需要的数据与 1.x 版本不一样，具体示例可以查看

- https://github.com/sakitam-fdd/wind-layer/blob/master/examples/wind-particles.html
- https://github.com/sakitam-fdd/wind-layer/blob/master/examples/wind-arrow.html
- https://github.com/sakitam-fdd/wind-layer/blob/master/examples/timeline-pattern.html
