### ISSUE TITLE
调试源码时playground运行失败

### ISSUE THREAD

**Issue by chen21439** [sakitam-fdd/wind-layer#198]
i run 
```sh
pnpm i
pnpm run build # cd ./packages/core 打包wind-core
pnpm add wind-core -r
pnpm run build # cd ./packages/ol 打包ol-wind
pnpm add ol-wind -r
```

问题出现在添加windLayer时,不添加则不会出现error

![image](https://github.com/sakitam-fdd/wind-layer/assets/141226184/1f2618c2-a179-43e0-b40c-4367ca22c907)

**Comment by chen21439** [comment]
![image](https://github.com/sakitam-fdd/wind-layer/assets/141226184/9393ea04-7e15-474d-bfaf-3f736a08938f)

**Comment by sakitam-fdd** [comment]
@chen21439 直接根目录执行
```bash
pmpm i

pnpm run dev
# or
pnpm run build
# or
pnpm run build:minify
```

关于 workspaces 的概念可以查看这个 https://pnpm.io/zh/workspaces

**Comment by chen21439** [comment]
> @chen21439 直接根目录执行
> 
> ```shell
> pmpm i
> 
> pnpm run dev
> # or
> pnpm run build
> # or
> pnpm run build:minify
> ```
> 
> 关于 workspaces 的概念可以查看这个 https://pnpm.io/zh/workspaces

- 一样的,主要就是运行playground时报错,我是用的node是17.9.1,拉取的是最新版本的代码

```
pmpm i
pnpm run dev
pnpm run build
pnpm run build:minify
```

**Comment by chen21439** [comment]
当我将plyaground中package.json中引用的ol-wind(^1.1.4)和wind-core(^1.1.3)改成使用npm下载时,playground项目就正常运行

**Comment by chen21439** [comment]
我看到依赖中有旧版本的openlayer4.6.5,不知道是不是这个原因引起的。

**Comment by chen21439** [comment]
![image](https://github.com/sakitam-fdd/wind-layer/assets/141226184/c4c9b2ee-db73-4844-bedb-b0c100b0b074)
![image](https://github.com/sakitam-fdd/wind-layer/assets/141226184/4dde8849-6c96-4e1d-b344-6d21a3cb39db)
npm上ol-wind现在的版本是1.14,github上最新的release是1.12,麻烦你更新一下哈

**Comment by sakitam-fdd** [comment]
@chen21439 

1. 添加图层报错的问题我这边本地无法复现，这个比较奇怪
![image](https://github.com/sakitam-fdd/wind-layer/assets/19517451/b277683d-71ea-43ff-aa03-1da0def43ce2)
![image](https://github.com/sakitam-fdd/wind-layer/assets/19517451/197fb59d-e84a-4f68-8bce-c711a556f005)
2. release 更新可能得过段时间，有几个功能没开发完
3. 这里有一个我这边打包的 ol
[dist.zip](https://github.com/sakitam-fdd/wind-layer/files/14395147/dist.zip)

**Comment by sakitam-fdd** [comment]
@chen21439 可能原因是 github 代码不是最新的，关于 ol 的后面有些修改，我这两周整理一下更新一下

**Comment by sakitam-fdd** [comment]
更新一下代码再试下：

pnpm 会自动处理依赖关系，不需要手动执行 `pnpm add pkg -r`

```bash
git pull

pnpm i

cd ./packages/core
pnpm run build
cd ../ol
pnpm run build
cd ../../playground/
pnpm start
```

另外 npm 和 github的release 已更新，此问题先关闭
