### ISSUE TITLE
请问手机端显示怎么处理（ratio=1）

### ISSUE THREAD

**Issue by newcookie** [sakitam-fdd/wind-layer#2]
![mobile-issue1](https://user-images.githubusercontent.com/26321372/34554382-8b86e552-f167-11e7-85a9-e931e2e887bd.png)

![image](https://user-images.githubusercontent.com/26321372/34555309-fc009388-f16b-11e7-874b-8055ba673a30.png)

**Comment by newcookie** [comment]
已解决，map配置pixelRatio为1就可以了啊啊啊啊啊

**Comment by sakitam-fdd** [comment]
@newcookie 赞一个
