### ISSUE TITLE
如何获取某一点的经纬度

### ISSUE THREAD

**Issue by wangfpp** [sakitam-fdd/wind-layer#20]
文档没有说明

**Comment by sakitam-fdd** [comment]
@wangfpp 这个完全是可以根据各个地图引擎的鼠标移动事件去获取啊，还是我理解错了你的意思？

**Comment by wangfpp** [comment]
感谢你的回复,已经找到了这个获取的方的
`map.on('click', event => {
          let arr = ol.proj.toLonLat(event.coordinate);
});
`

**Comment by wangfpp** [comment]
@sakitam-fdd 
感谢你能回复,我找到了这个方法：
`map.on('click', event => { let arr = ol.proj.toLonLat(event.coordinate); });`
