### ISSUE TITLE
引入mapbox-wind找不到ScalarFill、WindLayer等类

### ISSUE THREAD

**Issue by zym-2020** [sakitam-fdd/wind-layer#203]
按照示例写demo，在引入ScalarFill、WindLayer时找不到相关类，请问是我漏掉了什么吗？感谢您的回复！

**Comment by sakitam-fdd** [comment]
@zym-2020  ScalarFill、WindLayer 相关接口请使用 1.x 版本, 2.x与 1.0 版本不兼容，包括图层组织方式和数据提供方式都有较大的不同
