### ISSUE TITLE
风场跨东西半球，风场只显示一半的问题

### ISSUE THREAD

**Issue by kingerpk** [sakitam-fdd/wind-layer#205]
有个业务刚好在南太平洋上，跨了东西半球，在这个范围风场只出现在一边，这要怎么处理呢？

![风场1](https://github.com/sakitam-fdd/wind-layer/assets/2526822/88f1e5ef-7cd3-4f63-800c-dfca89594601)
![风场2](https://github.com/sakitam-fdd/wind-layer/assets/2526822/6bc67e71-2f98-4abc-b239-d261170d4f11)

**Comment by sakitam-fdd** [comment]
有测试数据吗，有个wrapX参数可以试着配置一下
https://github.com/sakitam-fdd/wind-layer/blob/b27a903f89913e1f580d1725669427c68fa3a5d5/examples/mapbox.html#L132

**Comment by kingerpk** [comment]
没看到之前已经有人提了这个问题，已经解决了，非常感谢

**Comment by chenkhcn** [comment]
> 没看到之前已经有人提过这个问题了，已经解决了，非常感谢

请问是怎么解决的
