### ISSUE TITLE
启动之后解析不了数据

### ISSUE THREAD

**Issue by newlifebegins** [sakitam-fdd/wind-layer#21]
![image](https://user-images.githubusercontent.com/16969582/54414032-be690000-4732-11e9-8965-c2f840fb9b68.png)

**Comment by sakitam-fdd** [comment]
下周我抽空查一下问题，你是部署在linux环境下的吗

**Comment by newlifebegins** [comment]
我是在window上面部署的

**Comment by newlifebegins** [comment]
> 下周我抽空查一下问题，你是部署在linux环境下的吗

我是在windows上部署的

**Comment by sakitam-fdd** [comment]
@newlifebegins v0.0.7版本再试下，我这边win、linux测试都无问题

**Comment by newlifebegins** [comment]
![image](https://user-images.githubusercontent.com/16969582/54736012-03ce7700-4be4-11e9-8a97-3b75f89428bf.png)
这个是不是没有下载全了

**Comment by newlifebegins** [comment]
![image](https://user-images.githubusercontent.com/16969582/54736038-26609000-4be4-11e9-9e39-a5bc690d6da8.png)
parseData这个文件夹中没有解析到数据，sourceData这个文件夹中有数据

**Comment by sakitam-fdd** [comment]
@newlifebegins 这个默认配置是仅抓取1000 hPa的数据，sourceData是正常的；然后想问下你的jdk 版本是哪个版本的

**Comment by newlifebegins** [comment]
> @newlifebegins 这个默认配置是仅抓取1000 hPa的数据，sourceData是正常的；然后想问下你的jdk 版本是哪个版本的

我的jdk是1.7.0_80  这个对jdk版本有要求吗？

**Comment by sakitam-fdd** [comment]
@newlifebegins 试下这个原仓库是否可用https://github.com/weacast/weacast-grib2json
