### ISSUE TITLE
Issues with toggling the wind layer

### ISSUE THREAD

**Issue by arthuroaraujo** [sakitam-fdd/wind-layer#215]
I'm facing an issue while using the `addLayer` and `removeLayer` functions as described in the example provided at https://blog.sakitam.com/wind-layer/guide/leaflet.html. In the example, the same issue I'm experiencing is occurring. For instance, if we start with the wind layer and disable it, upon trying to re-enable it, it won't display on the screen. I would like to understand how to resolve this issue or if there's an alternative to ensure that the wind layer is properly displayed when re-enabled. Thank you in advance for any help or guidance.

**Comment by sakitam-fdd** [comment]
fixed on [leaflet-wind@1.2.0](https://github.com/sakitam-fdd/wind-layer/releases/tag/leaflet-wind%401.2.0)
