### ISSUE TITLE
mapbox-wind1.1.1-alpha.2版本，只能绘制屏幕的一半粒子效果

### ISSUE THREAD

**Issue by ParadiseWangXS** [sakitam-fdd/wind-layer#224]
import { WindLayer } from '@sakitam-gis/mapbox-wind'

 fetch('https://blog.sakitam.com/wind-layer/data/wind.json')
          .then(res => res.json())
          .then(data  =>{
            console.log(data);
            window.windLayer = new WindLayer('wind',data,{
              windOptions: {
                colorScale:"#ffffff",
                // velocityScale: 1 / 20,
                // paths: 5000,
                lineWidth:3,
                frameRate: 16,
                maxAge: 60,
                globalAlpha: 0.9,
                velocityScale: 0.01,
                // velocityScale: () => {
                // 	const zoom = map.getZoom();
                // 	return velocityScales[zoom] || 0.01
                // },
                // paths: 10000,
                paths: 3782,
              },
              // fieldOptions: {
              //   wrapX: true,
              // },
            })
            console.log(this.map,window.windLayer )
            window.windLayer.addTo(this.map);
![QQ_1721115775077](https://github.com/user-attachments/assets/12a12c1e-a558-4301-b5ed-65a164db30d0)

**Comment by ParadiseWangXS** [comment]
我看两个canvas的宽高都是一样的，但是只有一半的效果
![QQ_1721116026521](https://github.com/user-attachments/assets/57b21432-bb75-4e2d-bb43-2972751d7916)

**Comment by ParadiseWangXS** [comment]
找到问题的原因了，是因为canvas左移了，，重写对应的css就可以了，是我不仔细了

**Comment by sakitam-fdd** [comment]
@ParadiseWangXS 👍
