### ISSUE TITLE
对于风，他是矢量数据包含u和v，在组装数据成图片时，是否是将uv放入rg通道？

### ISSUE THREAD

**Issue by xiongleio** [sakitam-fdd/wind-layer#226]
对于风，他是矢量数据包含u和v，在组装数据成图片时，是否是将uv放入rg通道？

**Comment by sakitam-fdd** [comment]
目前是的，对于 tiff 来说直接存的是对应的 uv 的浮点数数据，对于 jpg 灰度图来说存的像素值计算如下：
r = (u - uMin) / (uMax - uMin) * 255
g = (v - vMin) / (vMax - vMin) * 255

**Comment by yxdragon** [comment]
官网leaflet的例子是用json可视化的，然而高精度的json数据，后端传输压力很大。我希望直接绘制nc，tif。或带范围信息的jpg，png。你们讨论的问题好像是关于如何用图片初始化风场图层的，然而我没找到关于这方面的例子。请给一点提示，或者相关链接，最好是leaflet的。

**Comment by xiongleio** [comment]
> 目前是的，对于 tiff 来说直接存对应的 uv 的浮点数数据，对于 jpg 灰度图来说存的像素值计算如下：
> 
> ```js
> r = (u - uMin) / (uMax - uMin) * 255
> g = (v - vMin) / (vMax - vMin) * 255
> ```

感谢，对于无效值该如何处理，是否可以将值映射到0~244,255作为无效值标记。

**Comment by luo-geng** [comment]
> > 目前是的，对于 tiff 来说直接存对应的 uv 的浮点数数据，对于 jpg 灰度图来说存的像素值计算如下：
> > r = (u - uMin) / (uMax - uMin) * 255
> > g = (v - vMin) / (vMax - vMin) * 255
> 
> 感谢，对于无效值该如何处理，是否可以将值映射到0~244,255作为无效值标记。

你好,请问无效值怎么处理. 因为最大风速和最小风速 归一化到0-255.无效值默认是0,归一化后无效值是在0-255区间的某个部分
