### ISSUE TITLE
在react中使用mapbox-wind和maplibre-wind报错

### ISSUE THREAD

**Issue by yudeqang** [sakitam-fdd/wind-layer#232]
复现代码仓库：https://github.com/yudeqang/react-windLayer-demo
在：src/app.js
node版本：20.11.1
操作系统：windows 11

本地启动项目后打开浏览器报错：
![image](https://github.com/user-attachments/assets/95fcad22-88aa-4263-92b4-ca20a8a01731)

**Comment by sakitam-fdd** [comment]
@yudeqang https://stackoverflow.com/questions/66159523/webpack-require-is-not-defined-here-map-bundle-doesnt-work

我觉得可能是 webpack 的问题，建议换 vite，或者 react-scripts eject 后修改 webpack.config.js，添加 

```js
 node: {
     global: false
 }
```

![image](https://github.com/user-attachments/assets/a4f18b91-a188-4857-9a7f-64464cf77e66)

![image](https://github.com/user-attachments/assets/ff03f150-45c5-4cba-9ea3-00d7834fe151)
