### ISSUE TITLE
解析grib数据不稳定，有没有不用java的推荐下

### ISSUE THREAD

**Issue by liuwuqingnian** [sakitam-fdd/wind-layer#24]
怎样知道某个点的风速

**Comment by tomcake** [comment]
是grib数据转换嘛，Java有个开源的grib2json项目。
只需要重新OPtion即可，可以站内搜下

**Comment by sakitam-fdd** [comment]
@liuwuqingnian 第一个问题，可以看下 https://software.ecmwf.int/wiki/display/GRIB/Releases

第二个问题可以看下：https://github.com/sakitam-fdd/wind-layer/blob/master/src/openlayers/index.js#L216
