### ISSUE TITLE
高德地图缩放，风粒子跟着缩放

### ISSUE THREAD

**Issue by sukaihua** [sakitam-fdd/wind-layer#245]
大佬您好，我用高德接入风场插件，地图的缩放，会改变风粒子的大小，地图层级越大，风粒子的线条越大，地图层级为1级时，风粒子线条就特别小，目前我没在文档上找到配置的方法，在issues中也没搜索到，这种情况怎么解决。

**Comment by sakitam-fdd** [comment]
@sukaihua 能提供一个复现示例吗

**Comment by sukaihua** [comment]
您好，今天早上，我在已关闭的issues中找到了一个类似的，我先按照方法修改下，不合适我再提问

**Comment by sukaihua** [comment]
大佬好，我想问下，粒子的大小会跟风速大小有关系么，风速越大，线条越长，目前我出现新的问题是，在同一个层级下， 风速小的地方线条显示正常，在风速大的地方线条就特别长，测试地址：http://121.41.32.248:8099/weatherHome，在环境遥感下面的森林火点菜单，账号：11111111，密码：11111111
![image](https://github.com/user-attachments/assets/092dccf5-74dc-4703-b0e8-df2a1abb2260)

**Comment by sakitam-fdd** [comment]
@sukaihua 是有关系的，风速越大，单位时间移动的距离就越长，在canvas上表现moveTo和lineTo之间距离就越远，粒子淡出效果是用 globalCompositeOperation 来实现的
