### ISSUE TITLE
风粒子绘制显示的不对，

### ISSUE THREAD

**Issue by sukaihua** [sakitam-fdd/wind-layer#246]
您好，同一份数据用amap-wind绘制，显示结果是不对的（第一张图），用leaflet-velocity绘制是正确的（第二张图），我一直没找到原因是什么问题，在用amap-wind的时候是不是数据格式处理的不对。
![amap-winder](https://github.com/user-attachments/assets/0ab1e4cc-bb6b-40f4-93ab-f8ad98e864fe)
<img width="1638" alt="leaflet-velocity" src="https://github.com/user-attachments/assets/8f592702-871a-41d1-be70-70cc994581cc">

数据文件：
[Uploading test.json…]()

**Comment by sukaihua** [comment]
数据文件：
[test.json](https://github.com/user-attachments/files/17501713/test.json)

**Comment by sukaihua** [comment]
@sakitam-fdd  麻烦大佬有时间帮忙看下数据

**Comment by sakitam-fdd** [comment]
@sukaihua q - 1253148931

**Comment by sukaihua** [comment]
加不上。我看有问题，我的 q - 6255728

**Comment by sukaihua** [comment]
@sakitam-fdd 加不上。我看有问题，我的 q - 6255728

**Comment by sukaihua** [comment]
加这个qq了，有个真实姓名，或者您加我的？ 6255728


sukaihua
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "sakitam-fdd/wind-layer"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年10月28日(星期一) 上午10:08
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [sakitam-fdd/wind-layer] 风粒子绘制显示的不对， (Issue #246)





 
@sukaihua q - 1253148931

**Comment by sakitam-fdd** [comment]
@sukaihua 再试试

**Comment by sukaihua** [comment]
已加上
