### ISSUE TITLE
地图层级缩放后，粒子速度变快了，粒子也变大了，跪求大佬

### ISSUE THREAD

**Issue by 16619924976** [sakitam-fdd/wind-layer#248]
地图层级缩放后，粒子速度变快了，粒子也变大了，跪求大佬
![Uploading 1731402507091.jpg…]()

**Comment by sakitam-fdd** [comment]
@16619924976 这个是这个是已知行为，风速是个固定值，单位时间移动的距离是个定值，地图放大当然是会变快，优化方案请查看这个 https://github.com/sakitam-fdd/wind-layer/issues/165#issuecomment-1260538225
