### ISSUE TITLE
高德地图下问题

### ISSUE THREAD

**Issue by tomcake** [sakitam-fdd/wind-layer#26]
1、风场与地图的对应有点问题，拖动、放大地图，风场图层对应有问题
2、风场方向有疑问？相同数据源，使用leaflet绘制跟wind-layer风向不一样。
修改了js文件中的坐标系无变化
3、粒子颜色问题，拖尾颜色无法修改，始终是灰色

**Comment by sakitam-fdd** [comment]
@tomcake 收到，我抽空查一下

**Comment by tomcake** [comment]
多谢回复，大神可以参考下leaflet-velocity。
另外数据转换那块，github上有个grib2json 项目,转换更加稳定。
只要重写Option类即可。
