### ISSUE TITLE
grib2的获取规则已经变了，已无法正常获取数据

### ISSUE THREAD

**Issue by liuwuqingnian** [sakitam-fdd/wind-layer#29]
参数 dir的规则稍微变动，多了一个   ‘/’

**Comment by sakitam-fdd** [comment]
@liuwuqingnian Hi, 如果有兴趣可以发个 pr，server 端的维护这边不能保证，生产的话建议自己做一套服务哦。

**Comment by ranmao** [comment]
我这边下载的gfs地图数据有一个范围，但是wind渲染出来小了很多，是怎么回事呢？
![image](https://user-images.githubusercontent.com/1316986/71776350-0d866700-2fcb-11ea-93cc-ca7e298a714e.png)

**Comment by sakitam-fdd** [comment]
@liuwuqingnian 解决自 https://github.com/sakitam-fdd/wind-layer/commit/95368f94337b40f95799109c8df074e2237599e9
