### ISSUE TITLE
Wind layer's width/height issue

### ISSUE THREAD

**Issue by imgorosabel** [sakitam-fdd/wind-layer#42]
Hi!
I have a problem with the wind layer's width and height. It takes just the 50% of the window width and height, even though the canvas width looks like it's the window's 100% width. I've tried fixing it with css, changing the projection, I've put console.logs in the OLWind.js file to see the width and height it is taking, but there's no way.

As you can see in the screenshot below, it's everything ok but the width and height:
<img width="1184" alt="imagen" src="https://user-images.githubusercontent.com/52005415/69714887-932f1100-1107-11ea-9dc2-ab516e37b28f.png">

When I resize the window it adjusts it's width and height, but it still gets fixed to 50%. The same happens to me with the example you put at jsfiddle...

Many thanks in advance, and thanks for the project development you're doing

**Comment by imgorosabel** [comment]
Hi again! I've found the issue. The problem was I have a computer with retina display, and since the pixel density is double, the canvas was literally divided by two. I've fixed it by adding to the return of the function buildBounds the multiplier window.devicePixelRatio:

return {x: x, y: y, xMax: width * window.devicePixelRatio, yMax: yMax * window.devicePixelRatio, width: width * window.devicePixelRatio, height: height * window.devicePixelRatio};

**Comment by imgorosabel** [comment]
It's not fixed yet. Now the bounds are ok, but the particle origin, bucket and endpoint is still the way it was before. This only happens with retina displays :(

**Comment by sakitam-fdd** [comment]
@imgorosabel Can you provide the system version and browser version?

**Comment by imgorosabel** [comment]
> @imgorosabel Can you provide the system version and browser version?

Mac OS X 10.14.6 and Firefox 70.0.1, but the same happens with Chrome 78.0.3904.108

**Comment by sakitam-fdd** [comment]
@imgorosabel Ok, will check the problem in these two days

**Comment by imgorosabel** [comment]
Great! Many thanks, if I can help you somehow let me know

**Comment by sakitam-fdd** [comment]
@imgorosabel 
Temporarily added a devicepixelratio parameter,But this can only solve the problem temporarily, not the optimal solution. Please keep paying attention.
```js
new OlWind(data, {
      layerName: 'data',
      projection: 'EPSG:4326',
      devicePixelRatio: window.devicePixelRatio,
      map: map,
      colorScale: [
        "rgb(36,104, 180)",
        "rgb(60,157, 194)",
        "rgb(128,205,193 )",
        "rgb(151,218,168 )",
        "rgb(198,231,181)",
        "rgb(238,247,217)",
        "rgb(255,238,159)",
        "rgb(252,217,125)",
        "rgb(255,182,100)",
        "rgb(252,150,75)",
        "rgb(250,112,52)",
        "rgb(245,64,32)",
        "rgb(237,45,28)",
        "rgb(220,24,32)",
        "rgb(180,0,35)"
      ],
      minVelocity: 0,
      maxVelocity: 10,
      velocityScale: 0.05,
      particleAge: 90,
      lineWidth: 1,
      particleMultiplier: 0.01,
    });
```

**Comment by imgorosabel** [comment]
Thanks, it works!! MANY MANY Thanks! I'll check for future updates
