### ISSUE TITLE
Error with openlayers 5.0.2

### ISSUE THREAD

**Issue by HymanL** [sakitam-fdd/wind-layer#43]
在使用过程中，发现这个过程不断的出错误。是我用的方式不对嘛？react 16.11.0 ol是5.0.2

错误：windLayer.esm.js:917 Uncaught (in promise) TypeError: this.get is not a function
    at OlWind.getMap (windLayer.esm.js:917)
报错指向这个方法：/**
   * get map
   */
  OlWindy.prototype.getMap = function getMap () {
    return this.get('originMap');
  };
下面贴上我的部分代码

**Comment by HymanL** [comment]
let map = new Map({
      controls: defaultControls({
        attribution: false,
        zoom: false,
        rotate: false,
      }).extend([]),
      layers: layers,
      target: this.refs.cesiumContainer,
      view: new View({
        projection: 'EPSG:4326',
        center: [117.509569, 38.346416],
        zoom: 14,
        minZoom: 12,
        maxZoom: 19,
      }),
    });
    Map.viewerObj = map;

    var wind = new windLayer.OlWind(out, {
      layerName: '',
      minResolution: undefined,
      maxResolution: undefined,
      zIndex: 6,
      projection: 'EPSG:4326',
      ratio: 1
    });
    map.addLayer(wind);

**Comment by sakitam-fdd** [comment]
@HymanL ol5+暂时请使用以下方式（PS: 后面会将ol 和 openlayers的包合并）：
```
import WindLayer from 'wind-layer/dist/OlWindy.esm.js';

var wind = new WindLayer(out, {
  layerName: '',
  minResolution: undefined,
  maxResolution: undefined,
  zIndex: 6,
  projection: 'EPSG:4326',
  ratio: 1
});
map.addLayer(wind);
```

**Comment by HymanL** [comment]
非常的感谢您的耐心解答。解决了现有问题，但是现在正在报Failed to execute 'appendChild' on 'Node': parameter 1 is not of type 'Node'的错误，我想是不是因为ol版本的问题。我研究一下，非常感谢



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "FDD"<notifications@github.com&gt;; 
发送时间: 2019年12月4日(星期三) 晚上6:06
收件人: "sakitam-fdd/wind-layer"<wind-layer@noreply.github.com&gt;; 
抄送: "Hyman"<736160261@qq.com&gt;; "Mention"<mention@noreply.github.com&gt;; 
主题: Re: [sakitam-fdd/wind-layer] Error with openlayers 5.0.2 (#43)




@HymanL ol5+暂时请使用以下方式（PS: 后面会将ol 和 openlayers的包合并）：
 import WindLayer from 'wind-layer/dist/OlWindy.esm.js'; var wind = new WindLayer(out, {   layerName: '',   minResolution: undefined,   maxResolution: undefined,   zIndex: 6,   projection: 'EPSG:4326',   ratio: 1 }); map.addLayer(wind);

**Comment by sakitam-fdd** [comment]
@HymanL https://codesandbox.io/s/ecstatic-lake-zfjgp
