### ISSUE TITLE
Add support for Openlayers 6

### ISSUE THREAD

**Issue by woodbri** [sakitam-fdd/wind-layer#48]
Add support for current code under Openlayers 6, I'm getting the following error.

```
TypeError: Argument 1 of Node.appendChild does not implement interface Node. seecast-ol6.e31bb0bc.js:11134:12
    replaceChildren https://example.com/seecast-ol6.e31bb0bc.js:11134
    renderFrame https://example.com/seecast-ol6.e31bb0bc.js:38003
    renderFrame_ https://example.com/seecast-ol6.e31bb0bc.js:35575
    animationDelay_ https://example.com/seecast-ol6.e31bb0bc.js:34383
    <anonymous> self-hosted:876
```
This works under OpenLayers 5.3.3

**Comment by sakitam-fdd** [comment]
Ok,in progress

**Comment by woodbri** [comment]
Here is the OL6 changelog in case it helps:
https://github.com/openlayers/openlayers/blob/master/changelog/upgrade-notes.md
Unfortunately it is not very complete or detailed.

**Comment by longyangzz** [comment]
> Ok,in progress

wait for ol 6.0 ,thanks

**Comment by sakitam-fdd** [comment]
@woodbri @longyangzz try [v0.1.2](https://github.com/sakitam-fdd/wind-layer/tree/v0.1.x), If you like, can you test the logic and performance problems under the next branch.
