### ISSUE TITLE
EPSG:4326数据导入问题！！！

### ISSUE THREAD

**Issue by wfmm1990** [sakitam-fdd/wind-layer#5]
大哥，我现在正在使用你的windLayer插件。
这个插件真是灰常牛逼，叹为观止。
我就想问问，这个插件能够加载EPSG：4326的数据吗？我看到测试数据out.json是EPSG：3857的，但是我使用国内的底图服务(4326)，把ol.view设置成4326之后风场效果就乱了~
然后就是，大哥，上哪去下载EPSG：4326的风场数据啊，我现在在做这个效果，风场用的你的windLayer，飞行轨迹用的你的ol3Echarts。我搞了好几天了，不知道怎么去下载EPSG：4326的风场数据，好纠结。
求求大哥帮忙啊！！！跪谢了！！！要不大哥看能不能在GIT上面上传一个EPSG：4326的json数据？求求大哥了！！！我180°弯腰鞠躬了！！！

**Comment by sakitam-fdd** [comment]
你好，这个问题不太好解决啊，内置渲染算法包括获取的数据都是3857的。
你可以看下这个 `https://github.com/cambecc/earth`, 和你有同样问题的 `https://github.com/Esri/wind-js/issues/30` 。我会修改算法测试一下，如果可以我再通知你，可能不会很快。

**Comment by wfmm1990** [comment]
要不你看看leaflet-velocity里面是怎么实现的，我看现在做风场效果的好多是在用这个，这个好像就能够加载4326的数据。

**Comment by sakitam-fdd** [comment]
嗯，有空我看下，应该还是基于图层的投影转换，测试好了我再通知你。

**Comment by sakitam-fdd** [comment]
@wfmm1990 刚刚看了一下，leaflet-velocity是不支持 4326投影的。针对wind-layer我修改了一下投影算法，切到 `https://github.com/sakitam-fdd/wind-layer/tree/wind-server` 分支，build 后查看示例，暂时支持了 4326 投影，可能会有问题，你再反馈我。

**Comment by wfmm1990** [comment]
@sakitam-fdd 嗨，大哥，你这个branche要怎么跑起来啊？我用SVN下到本地了，然后直接找到这个“E:\SVNRoot\windLayer\branches\wind-server\examples\index.html”页面，打开之后加载不出来东西，是不是要用node跑啊，机器没装node😂

**Comment by wfmm1990** [comment]
大哥，你QQ多少啊？能加你一个QQ吗？工作Q就行，我也是做WEBGIS的，希望以后能够多向你请教。拜托，180°鞠躬！！！






在 2018-01-30 22:52:31，"FDD" <notifications@github.com> 写道：


@wfmm1990 刚刚看了一下，leaflet-velocity是不支持 4326投影的。针对wind-layer我修改了一下投影算法，切到 https://github.com/sakitam-fdd/wind-layer/tree/wind-server 分支，build 后查看示例，暂时支持了 4326 投影，可能会有问题，你再反馈我。

**Comment by wfmm1990** [comment]
@sakitam-fdd 大哥，我QQ826468347，要不你加我，我有好多问题想向你请教~
