### ISSUE TITLE
修改数据精度为0.25没有任何变化

### ISSUE THREAD

**Issue by mytheshow** [sakitam-fdd/wind-layer#54]
我看到你的代码里面精度是1.0，我自己获取了0.25精度的数据并转为json，然而并没有发现有任何变化？我如何能达到真气网那种效果，当把地图缩放到某个城市后能够看到更精确的风向？下面的参数是否需要变化？
`
requestParams: {

    //lev_2_m_above_ground: 'on',

    lev_10_m_above_ground: 'on',

    //lev_surface: 'on',

    // var_TMP: 'off',

    var_UGRD: 'on',

    var_VGRD: 'on',

    subregion: 'on'

  }
`

**Comment by sakitam-fdd** [comment]
@mytheshow 这个是需要修改`serviceUrl` https://github.com/sakitam-fdd/wind-layer/blob/master/server/config/config.js#L4 的，默认对应关系如下：
- 间隔1度：https://nomads.ncep.noaa.gov/cgi-bin/filter_gfs_1p00.pl
-  间隔0.5度：https://nomads.ncep.noaa.gov/cgi-bin/filter_gfs_0p50.pl
-  间隔0.25度：https://nomads.ncep.noaa.gov/cgi-bin/filter_gfs_0p25.pl

但是数据量过大可能扛不住，建议可以使用不同层级对应不同粒子数量来解决这个问题

**Comment by mytheshow** [comment]
你好，我这里还是不行，我的代码：

![daima](https://user-images.githubusercontent.com/20468274/77506068-d162f400-6e9f-11ea-96ae-92dc914cdfad.png)


**缩放为整体对比图，风向是正确的：**
![zhengti](https://user-images.githubusercontent.com/20468274/77505812-23efe080-6e9f-11ea-9380-1fa94231b194.png)
![zhengti2](https://user-images.githubusercontent.com/20468274/77505829-2c481b80-6e9f-11ea-80a9-4f6e6cbdb3c5.png)

**当精度为0.25时对比图，我的风向全是一个方向；而 "真气网"精度0.25时，风向很清晰：**

![suofang2](https://user-images.githubusercontent.com/20468274/77505885-5994c980-6e9f-11ea-96c7-740efc8ce27d.png)
![suofang](https://user-images.githubusercontent.com/20468274/77506034-bb553380-6e9f-11ea-9094-f3a2abee729f.png)

**Comment by mytheshow** [comment]
大佬，有时间能否帮忙看看这里，不知道你有没有遇到这个问题( ⊙ o ⊙ )？

**Comment by sakitam-fdd** [comment]
@mytheshow 你使用的是哪个包哪个版本

**Comment by mytheshow** [comment]
当前最新的，直接clone下来的

**Comment by sakitam-fdd** [comment]
@mytheshow 关于数据这块我不能提供太多信息，但是实际的格点数据处理也并不复杂，这个需要你自行研究。另外我看了一下真气网，他应该使用的是leaflet对应的[插件](https://github.com/danwild/leaflet-velocity)，对应的你如果使用的ol地图类库的话可以查看此项目的[0.1版本](https://github.com/sakitam-fdd/wind-layer/tree/v0.1.x?files=1)，但是这个版本实际有一些无法解决的问题，比如地图不可旋转、投影变换、粒子控制等。对于真气网的效果这个效果涉及业务处理，只提供一个思路：
- 监听地图视图分辨率变化事件
- 在事件中处理粒子数量的基值particleMultiplier
- 重绘

**Comment by mytheshow** [comment]
好的，现在我用leafletVelocity做了，非常感谢！
