### ISSUE TITLE
ol5时风场图在页面显示不完全，只显示一部分

### ISSUE THREAD

**Issue by ceverpack** [sakitam-fdd/wind-layer#58]
![wind](https://user-images.githubusercontent.com/48933930/79951431-3fa0d380-84ab-11ea-9c57-3f9dcd4f3f89.png)

**Comment by ceverpack** [comment]
@sakitam-fdd 我现在需要做一个简易版风场图，根据一部分观测点计算出部分区域的风场图，观测点的数据只有经纬度，风向，风速。只依靠这些数据可以绘制风场图吗？有什么思路吗？如果可以的画，希望能够得到解答。

**Comment by ceverpack** [comment]
如果可以帮忙做的话就更好了，有偿的

**Comment by sakitam-fdd** [comment]
@ceverpack 这个完全可以根据观测点数据构造uv数据，但是如果你的观测点不够效果可能不行，最近有点忙不一定及时回复
