### ISSUE TITLE
ol6 加载风场时，粒子不会自动消失

### ISSUE THREAD

**Issue by zxjin001** [sakitam-fdd/wind-layer#61]
这是我的测试图：
http://note.youdao.com/noteshare?id=60807a144db789b2ae4532de6e3d0b72&sub=BC4E285DA8B24261840917C15F0A5650

**Comment by sakitam-fdd** [comment]
@zxjin001 今天会发一版，这边测试已经解决了

**Comment by zxjin001** [comment]
你好，麻烦你下 ol-wind 和 wind-core 的 npm 包也更新下，我在使用你的组件，感谢啦

**Comment by sakitam-fdd** [comment]
@zxjin001 npm 挂了，等恢复ing

**Comment by zxjin001** [comment]
> @zxjin001 npm 挂了，等恢复ing

是的，我更新发现还是旧的，去 npm 官网看了，才发现 npm 挂了

**Comment by zxjin001** [comment]
> @zxjin001 npm 挂了，等恢复ing

npm 已经修复，期待ing

**Comment by sakitam-fdd** [comment]
@zxjin001 已更新 Try v1.0.0-alpha.3
