### ISSUE TITLE
ol-6 创建的风层怎么关闭

### ISSUE THREAD

**Issue by a653398363** [sakitam-fdd/wind-layer#62]
你好，我想问下创建的风图层怎么关闭

**Comment by a653398363** [comment]
![image](https://user-images.githubusercontent.com/30554223/82114823-98554a80-9791-11ea-9b83-d5c954db10c5.png)
大佬，为什么我创建的都是线，不是粒子

**Comment by a653398363** [comment]
``// 风场加载
    initWind (data) {
      let _this = this
      console.log('initWind', data)
      const ress = require('../../../static/json/weather.json')
      console.log('ress', ress)
      if (_this.windLay) this.map.removeLayer(_this.windLay)
      // if (!data) return
      _this.windLay = new WindLayer(ress, {
        windOptions: {
          // colorScale: scale,
          globalAlpha: 1,
          velocityScale: 1 / 20,
          paths: 5000,
          // lineWidth: 2, // 线的宽度
          // particleMultiplier: 0.01,
          // eslint-disable-next-line no-unused-vars
          colorScale: [
            'rgb(36,104, 180)',
            'rgb(60,157, 194)',
            'rgb(128,205,193 )',
            'rgb(151,218,168 )',
            'rgb(198,231,181)',
            'rgb(238,247,217)',
            'rgb(255,238,159)',
            'rgb(252,217,125)',
            'rgb(255,182,100)',
            'rgb(252,150,75)',
            'rgb(250,112,52)',
            'rgb(245,64,32)',
            'rgb(237,45,28)',
            'rgb(220,24,32)',
            'rgb(180,0,35)'
          ],
          // colorScale: scale,
          generateParticleOption: true
        },
        // map: _this.map,
        projection: 'EPSG:4326'
      })
      this.map.addLayer(_this.windLay)
    },
我这样写的

**Comment by a653398363** [comment]
大神，刚看之前别个提的，更新了版本，我只想说请收下我的膝盖

**Comment by a653398363** [comment]
大佬，还是请教一下创建的风图层怎么关闭啊，在线等..... @sakitam-fdd

**Comment by sakitam-fdd** [comment]
@a653398363 使用的哪个版本，对应类库

**Comment by a653398363** [comment]
1.0.0-alpha.3 @sakitam-fdd

**Comment by a653398363** [comment]
> @a653398363 使用的哪个版本，对应类库
1.0.0-alpha.3

**Comment by sakitam-fdd** [comment]
@a653398363 openlayer6的话可以直接调用map.removeLayer(layer)，是不起作用吗？

**Comment by a653398363** [comment]
> @a653398363 openlayer6的话可以直接调用map.removeLayer(layer)，是不起作用吗？

对，removeLayer不起作用，我想到个方法，获取canvas 然后把canvas dom 删掉

**Comment by sakitam-fdd** [comment]
@a653398363 收到，夜里我查一下

**Comment by a653398363** [comment]
> @a653398363 收到，夜里我查一下

大佬很厉害啊，还有个问题
![image](https://user-images.githubusercontent.com/30554223/82119221-50452080-97af-11ea-80be-102e2c92872a.png)
如何把多边形相交的部分设为虚线啊

**Comment by sakitam-fdd** [comment]
@a653398363 我试了一下是起作用的啊：https://codesandbox.io/s/map-ol-wind-2vc8v
CDN自行构建的样例：https://codepen.io/sakitam-fdd/pen/NWGOBoj.
另外可以更新到 1.0.0-alpha.4，修复了ol6 cdn引用的问题。
关于边界的那个问题，目前我所知的应该没有现成api做空间拓扑处理，它本身也是虚线，只不过多个边界叠一起后看起来不是虚线，这个真正处理起来会比较麻烦。

**Comment by a653398363** [comment]
> @a653398363 我试了一下是起作用的啊：https://codesandbox.io/s/map-ol-wind-2vc8v
> CDN自行构建的样例：https://codepen.io/sakitam-fdd/pen/NWGOBoj.
> 另外可以更新到 1.0.0-alpha.5，修复了ol6 cdn引用的问题。
> 关于边界的那个问题，目前我所知的应该没有现成api做空间拓扑处理，它本身也是虚线，只不过多个边界叠一起后看起来不是虚线，这个真正处理起来会比较麻烦。

嗯嗯，我在家测试了一下，用removeLayer 方法移除没得问题。厉害！！！
