### ISSUE TITLE
examples里的mapbox风场图有黄色的遮盖底色

### ISSUE THREAD

**Issue by QJvic** [sakitam-fdd/wind-layer#69]
![image](https://user-images.githubusercontent.com/17841191/86342599-6c7f1d00-bc8a-11ea-94bc-24665597b837.png)
如图所示，代码地址：https://codepen.io/qjvic/pen/QWyabVK
请问下是哪边要设置什么吗？万分感谢！

**Comment by QJvic** [comment]
map.addLayer(fillLayer);   有个覆盖图层，取消添加即可。

**Comment by sakitam-fdd** [comment]
@QJvic 色斑图是仿windy效果的，你可以看下这个：https://codepen.io/sakitam-fdd/pen/pogeoGP
