### ISSUE TITLE
npm run serve error:Module not found: Error: Can't resolve 'worker_threads' 

### ISSUE THREAD

**Issue by QJvic** [sakitam-fdd/wind-layer#70]
mapbox项目。
使用:
yarn add wind-core
yarn add wind-gl-core
yarn add @sakitam-gis/mapbox-wind
在代码中按照示例使用时，出现报警：
Module not found: Error: Can't resolve 'worker_threads' 
无法绘制风场图

**Comment by QJvic** [comment]
已解决 0.0 
报警不影响运行
运行是我自己代码出现问题了

**Comment by sakitam-fdd** [comment]
@QJvic 这个确实有点问题，发布到npm的少 ts 的类型定义文件，周末的版本会修一下

**Comment by sakitam-fdd** [comment]
try v1.0.0-alpha.10
