### ISSUE TITLE
Not able to get the particles for wrapX : true in ol6

### ISSUE THREAD

**Issue by HimaliPatil** [sakitam-fdd/wind-layer#71]
When adding the layer on ol6 map, the particles appear only for 0th world that is for -180 to +180. I want it to be in all panes.Is there any way to achieve this?

**Comment by sakitam-fdd** [comment]
This is still in progress, it is not complicated to implement this function, but it will greatly affect performance，I will reconsider this feature

**Comment by puxinyu** [comment]
+1，请问 ol5-wind 有方法实现吗？我想尝试添加但是能力不够[哭泣]

**Comment by sakitam-fdd** [comment]
@puxinyu 目前不太好实现，基于canvas绘制其他世界会极大影响性能，还没有好的方式优化

**Comment by sakitam-fdd** [comment]
@HimaliPatil 
1. https://blog.sakitam.com/wind-layer/guide/index#ol-wind-%E5%8F%82%E6%95%B0%E8%AF%B4%E6%98%8E
2. https://blog.sakitam.com/wind-layer/guide/index#fieldoptions-%E6%95%B0%E6%8D%AE%E9%85%8D%E7%BD%AE%E9%A1%B9%E8%AF%B4%E6%98%8E
