### ISSUE TITLE
关于高德地图amap-wind插件和wind-layer下AMapWind

### ISSUE THREAD

**Issue by alleluya-young** [sakitam-fdd/wind-layer#72]
@sakitam-fdd 大佬你好 请问高德地图用这两个实现风场区别是什么? 用哪个更适合一些? 谢谢

**Comment by sakitam-fdd** [comment]
@alleluya-young 从功能来讲新版amap-wind更好，但是新版有更差的性能😅，怎么选择取决你们业务，如果旧版功能能满足可以暂时先使用旧版

**Comment by alleluya-young** [comment]
> @alleluya-young 从功能来讲新版amap-wind更好，但是新版有更差的性能😅，怎么选择取决你们业务，如果旧版功能能满足可以暂时先使用旧版

旧版后续还会有更新吗 还是以新版amap-wind做后续迭代呢? 业务上目前用旧版满足使用 只是后续可能会做调整 可能考虑更新

**Comment by sakitam-fdd** [comment]
@alleluya-young 暂时是以新版做后续迭代，性能问题在想办法解决中
