### ISSUE TITLE
生成的背景图层和风向对应不上，又遇到过这个问题吗？背景图层是jsonArray

### ISSUE THREAD

**Issue by GofferdoXu** [sakitam-fdd/wind-layer#75]
`const fillLayer = new mapboxWind.ScalarFill('wind', {`
         ` "type": "jsonArray",`
         ` "data": data,`
         ` // "type": "image",`
          `// 'extent': [`
         ` //   [data[0]['header'].lo1, data[0]['header'].la1],`
          `//   [data[0]['header'].lo1, data[0]['header'].la2],`
         ` //   [data[0]['header'].lo2, data[0]['header'].la1],`
         ` //   [data[0]['header'].lo2, data[0]['header'].la2],`
         ` // ],`
         ` "extent": [`
          ` [-180, 85.051129],`
            `[-180, -85.051129],`
           ` [180, 85.051129],`
           ` [180, -85.051129],`
         ` ],`
          `"width": 1440,`
          `"height": 720,`
          `// "width": data[0]['header']['nx'],`
         ` // "height": data[0]['header']['ny'] - 1,`
         ` "min": -50.84996643066404,`
         ` "max": 42.25002441406252,`
         ` // "uMin": data[0]['header']['min'],`
         ` // "uMax": data[0]['header']['max'],`
         ` // "vMin": data[1]['header']['min'],`
          `// "vMax": data[1]['header']['max'],`
         ` "uMin": -21.34380340576172,`
          `"uMax": 30.7261962890625,`
         ` "vMin": -23.916271209716797,`
         ` "vMax": 24.693727493286133,`
       ` }, {`
         ` styleSpec: {`
            `'fill-color': [`
            `'interpolate',`
             ` ['linear'],`
             ` ['get', 'value'],`
             ` ...tempInterpolateColor`
           ` ],`
          ` 'opacity': 0.5`
         ` },`
         ` renderForm: 'rg',`
       ` });`

**Comment by sakitam-fdd** [comment]
@GofferdoXu 你是指粒子风速和色斑图颜色代表的风速对应不上吗

**Comment by lzio** [comment]
请问风场的色斑图是怎么生成的

**Comment by GofferdoXu** [comment]
> @GofferdoXu你是指粒子风速和色斑图颜色代表的风速对应不上吗

对的 对不上

**Comment by sakitam-fdd** [comment]
@lzio https://github.com/sakitam-fdd/wind-layer/tree/master/py-server

**Comment by sakitam-fdd** [comment]
@GofferdoXu 我加下测试看下

**Comment by sakitam-fdd** [comment]
@GofferdoXu @lzio try 1.1.0-alpha.0

**Comment by sakitam-fdd** [comment]
@lzio https://sakitam-fdd.github.io/wind-layer/api/#mapbox-scalarfill-layer
