### ISSUE TITLE
您好，我在openlayers中使用wind-layer时，频繁的执行removeLayer后重新addLayer，导致页面越来越卡，帧率越来越低

### ISSUE THREAD

**Issue by wanghanGiser** [sakitam-fdd/wind-layer#79]
请问执行removeLayer后，会有残留的任务在进行吗，为何会越来越卡呢

**Comment by sakitam-fdd** [comment]
@wanghanGiser 理论应该不会有，我会再抽空测试一下

**Comment by sakitam-fdd** [comment]
@wanghanGiser 确认是实例未执行销毁，下个版本会修复，谢谢反馈

**Comment by wanghanGiser** [comment]
感谢修复

**Comment by sakitam-fdd** [comment]
@wanghanGiser 可以提供下使用的 类库名称 + 版本吗？

**Comment by wanghanGiser** [comment]
"ol-wind": "^1.0.0-alpha.10"

**Comment by sakitam-fdd** [comment]
1. ol-wind 1.0.0-alpha.10 临时解决方案：
在调用 `map.removeLayer(windLayer)` 后执行
```js
const renderer = windLayer.getRenderer();
      if (renderer && renderer.oRender) {
        const executors = renderer.oRender.executors;
       Object.keys(executors).forEach((key) => {
            const wind = executors[key];
           if (wind) {
               wind.clearCanvas();
            }
         });
}
```

2. ol5-wind openlayers-wind 1.0.0-alpha.10 临时解决方案：
在调用移除图层的同时执行：
```js
windLayer.wind.clearCanvas()
```

新版晚点再发

**Comment by wanghanGiser** [comment]
> @wanghanGiser 可以提供下使用的 类库名称 + 版本吗？

"ol-wind": "^1.0.0-alpha.10"

**Comment by wanghanGiser** [comment]
> 1. ol-wind 1.0.0-alpha.10 临时解决方案：
>    在调用 `map.removeLayer(windLayer)` 后执行
> 
> ```js
> const renderer = windLayer.getRenderer();
>       if (renderer && renderer.oRender) {
>         const executors = renderer.oRender.executors;
>        Object.keys(executors).forEach((key) => {
>             const wind = executors[key];
>            if (wind) {
>                wind.clearCanvas();
>             }
>          });
> }
> ```
> 
> 1. ol5-wind openlayers-wind 1.0.0-alpha.10 临时解决方案：
>    在调用移除图层的同时执行：
> 
> ```js
> windLayer.wind.clearCanvas()
> ```
> 
> 新版晚点再发

好的感谢

**Comment by sakitam-fdd** [comment]
@wanghanGiser tryv1.1.1
