### ISSUE TITLE
清除图层之后就会出现setData就会报错！

### ISSUE THREAD

**Issue by z5614036** [sakitam-fdd/wind-layer#8]
![wxleys 8td i 7 t 6i](https://user-images.githubusercontent.com/24545834/37248309-fcf628a8-2509-11e8-9a6c-7b01e69e7dbc.png)

**Comment by z5614036** [comment]
![n389 5d8jz2axthliq ju1](https://user-images.githubusercontent.com/24545834/37248315-14456ee2-250a-11e8-91cd-00f56eb80c25.png)

**Comment by z5614036** [comment]
清除图层之后 再点击设置数据  就会出现这样的问题

**Comment by sakitam-fdd** [comment]
@z5614036 Yes, this is indeed a bug and I will fix it in the next release. But in fact you shouldn't set `data` after removing the layer. In the next version I will add the `removeLayer` method，this instance will be destroyed after remove，`clearWind` method will retain the instance.

**Comment by z5614036** [comment]
还有一个问题， 就是我修改了  view: new ol.View({
    projection: 'EPSG:3857',
    center: [0, 0],
    zoom:4
  })  中心坐标点，但地图定位的中心点没有改变

**Comment by sakitam-fdd** [comment]
@z5614036 事实上应该是有变化，EPSG:3857是墨卡托投影，不是经纬度坐标系，中国区可以试下 [12118909.300259633, 4086043.1061670054]，要使用经纬度坐标系的话projection应该设置为EPSG:4326:blush:。
