### ISSUE TITLE
色斑图如何使用呢？没有找到文档或示例？

### ISSUE THREAD

**Issue by PFSHI** [sakitam-fdd/wind-layer#84]
openlayers是否可以集成色斑图呢？没有找到有介绍文档或示例代码？

**Comment by TTorgersen** [comment]
Are you referring to the colorScale in windOptions?

**Comment by PFSHI** [comment]
> Are you referring to the colorScale in windOptions?

I mean the background layer that has a color gradient based on wind speed.

**Comment by sakitam-fdd** [comment]
> openlayers是否可以集成色斑图呢？没有找到有介绍文档或示例代码？

暂时没有ol的，不过可以换个方向，使用gl-core渲染Frambuff，然后使用image layer贴图

**Comment by sakitam-fdd** [comment]
@PFSHI @TTorgersen https://sakitam-fdd.github.io/wind-layer/api/#mapbox-scalarfill-layer
