### ISSUE TITLE
mapbox显示气温图，地图渲染的颜色与色标对应不上

### ISSUE THREAD

**Issue by voole** [sakitam-fdd/wind-layer#88]
在地图上0度以下的颜色与色标不对应，红色标记区域的温度应该是0度以下的
![image](https://user-images.githubusercontent.com/693011/104118344-44702500-5363-11eb-88a0-1c0593f54d3d.png)
通过工具显示grib数据如下图所示：
![image](https://user-images.githubusercontent.com/693011/104118363-6d90b580-5363-11eb-9e7f-914fcf76dff2.png)
使用的原始数据文件为：
[gfs.t12z.pgrb2.0p25.f000.zip](https://github.com/sakitam-fdd/wind-layer/files/5792409/gfs.t12z.pgrb2.0p25.f000.zip)

**Comment by sakitam-fdd** [comment]
@voole try 1.1.0-alpha.0

**Comment by ShareQiu1994** [comment]
> @voole try 1.1.0-alpha.0

大佬你好，我也正在用 ScalarFill API做单通道灰色图做气象彩色图， 在1.0.0版本中，在某些情况下出现了色标对不上的情况，看你你的回答，我使用了1.1.1的版本，色彩需要效果基本符合预期，但是性能巨卡。。在1.0.0没有这个问题

**Comment by ShareQiu1994** [comment]
同样代码、数据  灰度图在不同版本下的渲染彩色结果
1.1.0 效果
![HRUDV`%PCR B}QJ3ONIM (A](https://user-images.githubusercontent.com/19948086/115809737-3e3c1b00-a41f-11eb-8231-526e32cd898f.png)

1.1.1 效果
![image](https://user-images.githubusercontent.com/19948086/115809302-6b3bfe00-a41e-11eb-91ce-b6b00b59951e.png)
