### ISSUE TITLE
大佬，如果我用高德地图或者百度地图应该怎么调

### ISSUE THREAD

**Issue by ssshem** [sakitam-fdd/wind-layer#9]
最近要做一个类似earth.nullschool.net、windy.com的风场，采用的是百度地图，一直没有头绪，要歇菜了

**Comment by sakitam-fdd** [comment]
你这是只要效果还是做行业内的数据？还有你拿到的数据模型是什么样的，如果只是做效果还是比较好扩展，业内精确数据的现在还有问题。link #7

**Comment by ssshem** [comment]
@sakitam-fdd 谢谢你的回复。我拿到的数据模型也是grib2文件（气象局里的数据），用gribapi处理成json数据格式。我用过wind-js，但是它在百度地图上渲染显示的不是正常的，应该是wind-js原本支持arcgis地图，而两个地图的坐标系不一致导致渲染失败，但我对坐标系之类的很懵，我不是gis行业的，无奈

**Comment by sakitam-fdd** [comment]
@ssshem 周末我可以试着兼容一下百度和高德的，现阶段也只能保证可以渲染，数据现在是会有偏移，目前还没有好的解决办法，可能需要尝试一下 `web-gl` 方式，短时间内可能不太好解决 link #3 。

**Comment by ssshem** [comment]
@sakitam-fdd 谢谢:-D

**Comment by sakitam-fdd** [comment]
@ssshem 查看实例，现在投影有问题，只能算是有效果，其他的只能后续再修复。

**Comment by ssshem** [comment]
@sakitam-fdd  谢谢大哥，给你个赞

**Comment by ssshem** [comment]
fdd，我上周用百度的echarts实现风场，但它是基于webgl渲染的，结果特别慢，而且cpu占用特别大，所以我不建议尝试去用webgl

**Comment by sakitam-fdd** [comment]
@ssshem 我觉得你可能是用的假的 `web-gl` :smirk:, ()[https://github.com/mapbox/webgl-wind]
