### ISSUE TITLE
调用clearCanvas后，移动或者缩放地图，风场又会重新渲染

### ISSUE THREAD

**Issue by TroyBug** [sakitam-fdd/wind-layer#96]
目前使用的版本是`ol5-wind v1.1.0-alpha.0`，`openlayers`版本是`v5.3.0`，我使用了以下代码来关闭风场图：
```javascript
windLayer.wind.clearCanvas()
map.removeLayer(windLayer)
```
但之后如果拖动地图或者缩放，风场又重新出现在屏幕上，看了下源码，似乎没有提供类似destroy的接口，
请问这种情况应该如何完全销毁实例？

[codepen测试](https://codepen.io/TroyBug/pen/bGgewpv)

5秒后关闭风场，再次平移或缩放时风场又出现了

**Comment by sakitam-fdd** [comment]
@TroyBug duplicate #79，暂时可以这样处理一下，暂时还没好的处理方式，除非接管 map 的 removeLayer 方法

**Comment by Helr** [comment]
Hello, I think we tried to change the data in windlayers like this
你好，我觉得我们尝试这样更改windlayers里的数据
eg:
例如：
      let layer = new WindLayer(res,option)
      let field =  layer.getData(layer)
      this.windLayer.setData(field)
